version: "3.7"
services:
  speedtest:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "resultdata:/usr/src/app/data"
    ports:
      - 8080:80
      - 4343:443
    environment:
      - CRONJOB_ITERATION=15
volumes:
  resultdata: